In [1]:
import numpy as np

In [3]:
#Q1. Create a NumPy array of 10 random integers between 1 and 100. Find its mean.

arr = np.random.randint(1, 101, 10) 
arr

array([28, 33, 93, 87, 97,  6, 42, 86, 68, 83], dtype=int32)

In [7]:
mean = np.mean(arr)
mean

np.float64(62.3)

In [9]:
#Q2. Calculate the median of the array: [10, 5, 8, 12, 3, 7].

arr =  [10, 5, 8, 12, 3, 7]
median = np.median(arr)
median

np.float64(7.5)

In [10]:
#Q3. Generate an array of 15 random numbers between 1 and 50. Find its standard deviation.

arr = np.random.randint(1, 51, 15)
arr

array([22, 24, 20, 18, 34, 35,  9, 47, 24, 19, 47,  8, 14, 33, 32],
      dtype=int32)

In [11]:
std_deviation = np.std(arr)
std_deviation

np.float64(11.664571240393803)

In [12]:
#Q4. Create a 3x3 array with values from 1 to 9. Find the row-wise mean.

arr = np.arange(1, 10).reshape(3, 3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
row_mean = np.mean(arr, axis = 1)
row_mean

array([2., 5., 8.])

In [14]:
column_mean = np.mean(arr, axis =0)
column_mean

array([4., 5., 6.])

In [16]:
#Q5. For the array [4, 6, 8, 10, 12], calculate mean, median, std.

arr = [4,6,8,10,12]

mean = np.mean(arr)
median = np.median(arr)
std_dev = np.std(arr)

print("Mean:", mean, "Median:", median, "Standard Deviation:", std_dev)


Mean: 8.0 Median: 8.0 Standard Deviation: 2.8284271247461903


In [19]:
#Q6. Generate a 5x5 NumPy array of random integers (0 to 100). Find the overall mean.

arr = np.random.randint(0, 101, 25).reshape(5, 5)
arr

array([[68,  3, 20, 57, 83],
       [ 8, 73, 38, 37, 41],
       [87,  4, 69, 14, 39],
       [60, 35, 27, 15, 12],
       [39,  5, 63, 28, 46]], dtype=int32)

In [20]:
mean = np.mean(arr)
mean

np.float64(38.84)

In [21]:
row_mean = np.mean(arr, axis= 1) #Row-wise mean
row_mean

array([46.2, 39.4, 42.6, 29.8, 36.2])

In [22]:
column_mean = np.mean(arr, axis= 0) #Column-wise mean
column_mean

array([52.4, 24. , 43.4, 30.2, 44.2])

In [24]:
#Q7. Create an array of 50 random integers and calculate the standard deviation.

arr = np.random.randint(1, 500, 50)
arr

array([ 74, 288,  38, 304,  66, 261,  52, 300, 325,  81, 449, 486, 163,
       111, 409, 260, 249, 309, 107, 118,  72,  61, 398, 122, 453, 277,
        70, 148, 482, 397,  95,  55, 466, 122, 287, 128,  81,  57, 314,
       118, 185, 225, 129, 340,  84, 326, 154, 125,  88, 248], dtype=int32)

In [25]:
std_dev = np.std(arr)
std_dev

np.float64(134.91612357312968)

In [33]:
#Q8. Find indices of non-zero elements from [1,2,0,0,4,0]

arr = [1,2,0, 0, 4, 0]

indices = np.nonzero(arr)

print("Indices of non-zero elements:", indices[0])


Indices of non-zero elements: [0 1 4]


In [35]:
arr1 = np.array([1,2,0,0,4,0])

bool_index = (arr1 != 0)

print(bool_index)

[ True  True False False  True False]


In [38]:
non_zero_values = arr1[bool_index]
non_zero_values

array([1, 2, 4])

In [48]:
#Q9. Print 2D array elements

arr = np.array([
      [2,3,4,
       5,7,4,
       8,9,0]
]).reshape(3,3)

arr

array([[2, 3, 4],
       [5, 7, 4],
       [8, 9, 0]])

In [49]:
new_arr = arr[1, 1:]   # row 1, columns 1 onwards
print(new_arr)         # [7 4]


[7 4]


In [55]:
#Q10. Create 2 array of 2-Dimension and then perform matrix multiplication on them

arr1 = np.random.randint(1, 5, (2, 2))
arr2 = np.random.randint(1, 5, (2, 2))

In [56]:
result = np.matmul(arr1, arr2)
result

array([[20, 10],
       [28, 14]], dtype=int32)