In [1]:
import numpy as np

In [4]:
#Create a 1D array of integers from 10 to 50 with step 5.

arr = np.arange(10, 55, 5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [7]:
#Create a 2D array (3×3) with values ranging from 1 to 9.

arr = np.arange(1, 10).reshape(3, 3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
#Create an array of 10 zeros and an array of 10 ones.

arr_zeros = np.zeros(10)

arr_ones = np.ones(10)

print(arr_zeros)
print(arr_ones)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [10]:
#Generate an array of 20 random integers between 50 and 100.

arr = np.random.randint(50, 101, 20)
arr

array([97, 54, 67, 74, 62, 53, 93, 99, 57, 62, 62, 91, 90, 59, 95, 59, 84,
       90, 97, 67], dtype=int32)

In [11]:
#Create an identity matrix of size 4×4.

identity_matrix = np.identity(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])