In [1]:
import numpy as np

In [4]:
#Create an array of 12 elements and reshape it into a 3×4 matrix.

arr = np.arange(1, 13).reshape(3, 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
#Flatten a 2D array into a 1D array.

arr = np.arange(1, 10).reshape(3, 3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
flatten_array = arr.flatten()
flatten_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
flat1 = arr.ravel()
flat1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
flat2 = arr.reshape(-1)
flat2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#Stack two arrays vertically and horizontally.

arr1 = np.arange(1, 10)
arr2 = np.arange(11, 20)


In [19]:
vertical = np.vstack((arr1, arr2))
vertical

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [21]:
horizontal = np.hstack((arr1, arr2))
horizontal

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [23]:
column = np.column_stack((arr1, arr2))
column

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19]])

In [27]:
#Split a 1D array of 10 elements into 2 equal parts.

arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
np.split(arr, 2)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [31]:
#Convert a 1D array [1,2,3,4,5,6] into a 2D array of shape (2,3).

a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [32]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])