In [1]:
import numpy as np

In [10]:
#From [1,2,0,0,4,0], get indices of non-zero elements (two methods).

a = np.array([1, 2, 0, 0, 4, 0])

np.nonzero(a)

(array([0, 1, 4]),)

In [11]:
np.where(a != 0)

(array([0, 1, 4]),)

In [13]:
#Filter all elements divisible by 3 from [3,6,7,9,12,14,18].

arr = np.array([3,6,7,9,12,14,18])

bool_index = (arr % 3 ==0)
bool_index

array([ True,  True, False,  True,  True, False,  True])

In [15]:
arr[bool_index]

array([ 3,  6,  9, 12, 18])

In [16]:
#Create a 5×5 matrix of random numbers and replace all numbers greater than 50 with 0.

arr = np.random.randint(1, 101, 25).reshape(5, 5)
arr

array([[81, 49, 23, 36, 91],
       [61, 35,  2, 54, 98],
       [76, 40, 83, 44, 57],
       [27, 45, 28, 78, 82],
       [21, 51, 80,  8,  3]], dtype=int32)

In [17]:

bool_index = (arr > 50)
bool_index

array([[ True, False, False, False,  True],
       [ True, False, False,  True,  True],
       [ True, False,  True, False,  True],
       [False, False, False,  True,  True],
       [False,  True,  True, False, False]])

In [18]:
arr[bool_index] = 0

In [19]:
print(arr)

[[ 0 49 23 36  0]
 [ 0 35  2  0  0]
 [ 0 40  0 44  0]
 [27 45 28  0  0]
 [21  0  0  8  3]]


In [23]:
#Find all even numbers from a random array of size 15.

arr = np.random.randint(1, 100, 15)

evens = arr[arr % 2 == 0]
evens

array([10, 74, 22, 96, 52, 38, 50, 46,  8], dtype=int32)

In [25]:
#Replace negative values in a random array with their absolute values.

arr = np.random.randint(-10, 10, 10)
arr

array([ 9,  2,  4, -6,  3,  7, -4, -8,  6, -3], dtype=int32)

In [26]:

abs_arr = np.absolute(arr)
abs_arr

array([9, 2, 4, 6, 3, 7, 4, 8, 6, 3], dtype=int32)